version: '3'

services:
  db:
    image: mysql:5.7
    container_name: ${CONTAINER_NAME_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - WP-DOCKER

  wordpress:
    depends_on:
      - db
    build: Docker/Wordpress
    # image: wordpress:latest
    container_name: ${CONTAINER_NAME_APP}
    ports:
      - "${APP_PORT}:80"
    restart: always
    volumes:
      - .:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - WP-DOCKER

  node:
    build: Docker/Node
    container_name: ${CONTAINER_NAME_NODE}
    volumes:
      - .:/var/www/html
    tty: true
    expose:
      - 4200
    ports:
      - 4200:4200
      - 49152:49152

volumes:
  db_data:

networks:
  WP-DOCKER:
    external: true
